import os

def create_pcb(output_path):
    # Board dimensions: 54mm long x 19mm wide
    # Origin at (100, 100)
    x0 = 100.0
    y0 = 100.0
    w = 54.0
    h = 19.0
    r = 1.5  # rounded corner radius
    
    pcb_content = f"""(kicad_pcb
  (version 20231120)
  (generator "ControlledUsb_PCB_Builder")
  (generator_version "10.0")
  (general
    (thickness 1.6)
    (legacy_teardrops no)
  )
  (paper "A4")
  (title_block
    (title "ControlledUsb Dongle")
    (date "2026-10-01")
    (rev "v1.0")
    (company "ControlledUsb Open Hardware")
    (comment 1 "High-Speed USB 2.0 Host-Controlled Extension Dongle")
    (comment 2 "Stackup: JLCPCB JLC04161H 4-Layer (Top/GND/Power/Bottom)")
  )
  (layers
    (0 "F.Cu" signal)
    (1 "In1.Cu" power "GND")
    (2 "In2.Cu" power "PWR")
    (31 "B.Cu" signal)
    (32 "B.Adhes" user "B.Adhesive")
    (33 "F.Adhes" user "F.Adhesive")
    (34 "B.Paste" user)
    (35 "F.Paste" user)
    (36 "B.SilkS" user "B.Silkscreen")
    (37 "F.SilkS" user "F.Silkscreen")
    (38 "B.Mask" user)
    (39 "F.Mask" user)
    (40 "Dwgs.User" user "User.Drawings")
    (41 "Cmts.User" user "User.Comments")
    (42 "Eco1.User" user "User.Eco1")
    (43 "Eco2.User" user "User.Eco2")
    (44 "Edge.Cuts" user)
    (45 "Margin" user)
    (46 "B.CrtYd" user "B.Courtyard")
    (47 "F.CrtYd" user "F.Courtyard")
    (48 "B.Fab" user)
    (49 "F.Fab" user)
  )
  (setup
    (pad_to_mask_clearance 0)
    (allow_soldermask_bridges_in_footprints no)
    (pcbplotparams
      (layerselection 0x00010fc_ffffffff)
      (plot_on_all_layers_selection 0x0000000_00000000)
      (disableapertmacros no)
      (usegerberextensions yes)
      (usegerberattributes yes)
      (usegerberadvancedattributes yes)
      (creategerberjobfile yes)
      (dashed_line_dash_ratio 12.000000)
      (dashed_line_gap_ratio 3.000000)
      (svgprecision 4)
      (plotframeref no)
      (viasonmask no)
      (mode 1)
      (useauxorigin no)
      (hpglpennumber 1)
      (hpglpenspeed 20)
      (hpglpendiameter 15.000000)
      (pdf_front_fp_property_popups yes)
      (pdf_back_fp_property_popups yes)
      (dxfpadmode 0)
      (dxfshapemode 1)
      (dxfprecision 4)
      (dxfvias no)
      (dxftEXTmode 0)
      (dxfcoppercolor 0)
      (dxfusepcbnewfont yes)
      (outputformat 1)
      (mirror no)
      (drillshape 1)
      (scaleselection 1)
      (outputdirectory "gerber/")
    )
  )

  (gr_line (start {x0 + r} {y0}) (end {x0 + w - r} {y0}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_line (start {x0 + w} {y0 + r}) (end {x0 + w} {y0 + h - r}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_line (start {x0 + w - r} {y0 + h}) (end {x0 + r} {y0 + h}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_line (start {x0} {y0 + h - r}) (end {x0} {y0 + r}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_arc (start {x0 + w - r} {y0 + r}) (mid {x0 + w - r * 0.293} {y0 + r * 0.293}) (end {x0 + w} {y0 + r}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_arc (start {x0 + w} {y0 + h - r}) (mid {x0 + w - r * 0.293} {y0 + h - r * 0.293}) (end {x0 + w - r} {y0 + h}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_arc (start {x0 + r} {y0 + h}) (mid {x0 + r * 0.293} {y0 + h - r * 0.293}) (end {x0} {y0 + h - r}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))
  (gr_arc (start {x0} {y0 + r}) (mid {x0 + r * 0.293} {y0 + r * 0.293}) (end {x0 + r} {y0}) (stroke (width 0.15) (type solid)) (layer "Edge.Cuts"))

  (gr_text "ControlledUsb v1.0" (at {x0 + w/2} {y0 + 3.0} 0) (layer "F.SilkS")
    (effects (font (size 1.2 1.2) (thickness 0.2)))
  )
  (gr_text "HOST INPUT" (at {x0 + 6.0} {y0 + h/2} 90) (layer "F.SilkS")
    (effects (font (size 0.9 0.9) (thickness 0.15)))
  )
  (gr_text "SWITCHED OUTPUT" (at {x0 + w - 6.0} {y0 + h/2} 90) (layer "F.SilkS")
    (effects (font (size 0.9 0.9) (thickness 0.15)))
  )
)
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(pcb_content)
    print(f"Created initial PCB: {output_path}")

if __name__ == "__main__":
    create_pcb("d:/Projects/ControlledUsb/hardware/ControlledUsb.kicad_pcb")
